### ISSUE TITLE
Update to accurate Sample Response Body in Apiary

### ISSUE THREAD

**Issue by oliviajlin-zz** [sygmo/cs373-idb#15]
Currently all the Sample Response Bodies (constellations, family, moon, planet, stars) show  "id": 1,  "name": "Draco",  "meaning": "dragon".... - waiting on an accurate models.py so that the Sample Response Body can be updated according to models.py's columns.

**Comment by oliviajlin-zz** [comment]
Make Apiary changes according to models.py (exoplanet and planet attributes - length of day, parallax, orbital period have changed).

**Comment by mknocke** [comment]
Remove length of year from planets (not exoplanets) and parallax from star

**Comment by oliviajlin-zz** [comment]
Removed:  length of year from planets (not exoplanets) and parallax from star
